package com.workmate.domain.conversation;

/**
 * The role of the author of a {@link Message} within a {@link Conversation}.
 *
 * <p>Mirrors the standard LLM chat-completion role taxonomy so that the domain
 * model is portable across AI providers without translation.
 */
public enum MessageRole {

    /** A message authored by the human end-user. */
    USER,

    /** A message generated by the AI assistant. */
    ASSISTANT,

    /** A system-level instruction that shapes assistant behaviour. */
    SYSTEM,

    /** A result returned by an external tool / function call. */
    TOOL
}
